const MAIN_SCREEN_APP_BAR_TITLE = "Discover";
const MAIN_SCREEN_BEST_POPULAR_MOVIES_AND_SERIALS =
    "BEST POPULAR MOVIES AND SERIALS";
const MAIN_SCREEN_CHECK_MOVIE_SHOWTIMES = "Check Movie\nShowTImes";
const MAIN_SCREEN_SEE_MORE = "SEE MORE";
const SHOW_CASES_TITLE = "SHOWCASES";
const SHOW_CASES_SEE_MORE = "MORE SHOWCASES";
const BEST_ACTOR_TITLE = "BEST ACTORS";
const BEST_ACTOR_SEE_MORE = "MORE ACTORS";
const ACTORS_TITLE = "ACTORS";
const CREATORS_TITLE = "CREATORS";
const CREATORS_SEE_MORE = "MORE CREATORS";
const MOVIE_DETAILS_STORYLINE_TITLE = "STORYLINE";
const MOVIE_DETAILS_SCREEN_RELATED_MOVIES = "Related Movies";
